services:
  db:
    image: postgres:15
    container_name: yuruppang-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: yuruppang-app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data:
