services:
  db:
    image: postgres:17
    container_name: yuruppang-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: inwooinwoo/yuruppang:latest
    container_name: yuruppang-app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"

  fastapi:
    image: inwooinwoo/fastapi-app:latest
    container_name: fastapi-app
    restart: always
    depends_on:
      - db
      - app

volumes:
  postgres_data:
