services:
  db:
    image: postgres:17
    container_name: yuruppang-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: inwooinwoo/yuruppang:latest
    container_name: yuruppang-app
    restart: always
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    ports:
      - "8080:8080"

  fastapi-app:
    image: inwooinwoo/commute-mate:latest
    container_name: fastapi-app
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:8001:8000"  # Nginx proxy용
      
volumes:
  postgres_data:
