spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:file:./data/yuruppang-dev-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
